### ISSUE TITLE
How to handle pinning

### ISSUE THREAD

**Issue by DougAnderson444** [abhiyerra/ipswarm#2]
Did you come up with a design on how to handle pinning, seeing as serverless doesn't come with storage? Curious to hear your thoughts on the storage/pinning aspect!

**Comment by abhiyerra** [comment]
To be honest I haven't done anything with pinning. I am just pulling it directly. Since I am using the API I guess I could just add a condition to pin it locally when I get a new pubsub and run a clean up when the app is shut down. But to be honest, I haven't considered it yet.
